#!/bin/bash -l

# Set SCC project
#$ -P tuberculosis

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=50:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m abe

# Give job a name
#$ -N poonam

# Request cores
#$ -pe omp 16

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o 02e_Run_Bowtie2.qlog

# Submit an array job with n tasks
#$ -t 1

# ask for scratch space
#$ -l scratch=100G

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

# Setup
module load samtools
module load bowtie2
stem="/restricted/projectnb/tuberculosis/work/aubrey/Alland_TB/02_23_23_coverage"
nthreads=16

while read which fasta_out FASTA seq1 seq2
do
out_title=${which}_${fasta_out}
echo $out_title
index=${stem}/Indices/${fasta_out}
bowtie2-build --quiet --threads $nthreads -f $FASTA $index
echo "Else invoked"
bowtie2 --no-unal --threads $nthreads -x $index -1 $seq1 -2 $seq2 -S $stem/Alignments/${out_title}.sam --very-fast-local
# Convert to BAM and then sort
samtools view -bS $stem/Alignments/${out_title}.sam > $stem/Alignments/${out_title}.bam
samtools sort $stem/Alignments/${out_title}.bam -o $stem/Alignments/${out_title}.sorted.bam
samtools index $stem/Alignments/${out_title}.sorted.bam
rm -rf $stem/Alignments/${out_title}.sam $stem/Alignments/${out_title}.bam
done < ${stem}/all_file_combos_e.txt

echo "DONE!"

# for unpaired, replace -1 -2 with -U $raw
