#!/bin/bash -l

# Set SCC project
#$ -P tuberculosis

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=24:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N blast

# Request eight cores
#$ -pe omp 8

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o blast_fasta.qlog

#   ask for scratch space
#$ -l scratch=100G

# Submit an array job with n tasks
#$ -t 1

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

# Keep this location! BLAST database location!
# cd /restricted/projectnb/pathoscope/data/blastdb/nt

### SETUP
PE_loc="/restricted/projectnb/tuberculosis/work/aubrey/Alland_TB/05_01_23_Pangenome/"

module load blast+

# Make a custom database from fasta file of seqs
makeblastdb –in ${PE_loc}/PE_PPE_genes.fasta –dbtype nucl –parse_seqids  

blastn -query ${PE_loc}/BCCM_083.fasta -db PE_PPE_genes -out PE_PPE_BlastResults.csv -outfmt " 17 10 qseqid sacc sscinames score evalue"

