#!/bin/bash -l

# Set SCC project
#$ -P johnsonlab

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=24:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N db_uniprot

# Request eight cores
#$ -pe omp 2

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o db_uniprot.qlog

#   ask for scratch space
#$ -l scratch=100G

# Submit an array job with n tasks
#$ -t 1

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

module load blast+

#wget https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz
#gunzip -v uniref90.fasta.gz
makeblastdb -in uniref90.fasta -dbtype prot -input_type fasta -out uniref90.fasta

#bin/pfilt uniref90.fasta > uniref90filt
#makeblastdb -dbtype prot -in uniref90filt -out uniref90filt
