#!/bin/bash -l

# Set SCC project
#$ -P johnsonlab

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=24:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N download_uniprot

# Request eight cores
#$ -pe omp 1

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o download_uniprot.qlog

#   ask for scratch space
#$ -l scratch=100G

# Submit an array job with n tasks
#$ -t 1

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

# Downloaded from this site, only90% identity
# https://www.uniprot.org/uniref?query=%28identity%3A0.9%29

curl -o uniprot_accessed_90.tsv \
-H "Accept: text/plain; format=tsv" "https://rest.uniprot.org/uniref/stream?compressed=true&fields=id%2Cname%2Ctypes%2Ccount%2Corganism%2Clength%2Cidentity&format=tsv&query=%28%28identity%3A0.9%29%29"