#!/bin/bash -l

# Set SCC project
#$ -P johnsonlab

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=48:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N run_uniprot

# Request eight cores
#$ -pe omp 16

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o run_uniprot.qlog

#   ask for scratch space
#$ -l scratch=100G

# Submit an array job with n tasks
#$ -t 1

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

# Keep this location! BLAST uniprot database location!
cd /restricted/projectnb/tuberculosis/work/aubrey/Alland_TB/TB_pangenome_scripts/Uniprot/uniprot_db

### SETUP
dataDir=/restricted/projectnb/tuberculosis/work/aubrey/Alland_TB/TB_pangenome_scripts/Uniprot
fastaDir=$dataDir/blast_fastas
inputs=(${fastaDir}/Accessory_Gene_Prot_Seqs.fasta)
index=$(($SGE_TASK_ID-1))
fastafile=${inputs[$index]##*/}
sampleName=${fastafile%%.fasta}

echo $sampleName

module load blast+

# https://www.metagenomics.wiki/tools/blast/blastn-output-format-6
blastp -query $fastaDir/$fastafile \
-db uniref90.fasta \
-out $fastaDir/${sampleName}_uniprotBlastResults.csv \
-num_threads 16 \
-max_target_seqs 5 \
-outfmt 6

echo "Done!"
